apiVersion: v1
kind: Service
metadata:
  name: techtrends
  labels:
    app: techtrends
  namespace: sandbox
spec:
  type: ClusterIP
  ports:
    - port: 4111
      targetPort: 3111
      protocol: TCP
      name: http
  selector:
    app: techtrends
