# Default values for techtrends.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace:
  name: demo

service:
  port: 3111
  type: ClusterIP
  nodePort: 30007

image:
  repository: codepoetme/techtrends
  pullPolicy: IfNotPresent
  tag: "latest"

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: 3111
readinessProbe:
  httpGet:
    path: /healthz
    port: 3111
