# Default values for techtrends.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace:
  name: demo

service:
  port: 8111
  type: ClusterIP

image:
  repository: codepoetme/techtrends
  pullPolicy: IfNotPresent
  tag: "latest"

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /status
    port: http
readinessProbe:
  httpGet:
    path: /status
    port: http
